# Generated by Django 4.2.3 on 2026-06-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_snapchatuser_phone_number_rechargerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('offer_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.RemoveField(
            model_name='rechargerequest',
            name='amount',
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='offer_type',
            field=models.CharField(choices=[('free_boost', 'Boost Gratuit'), ('premium_week', 'Premium 1 Semaine'), ('unlimited', 'Illimité'), ('standard', 'Standard')], default='free_boost', max_length=20),
        ),
        migrations.AddField(
            model_name='snapchatuser',
            name='platform_clicked',
            field=models.CharField(blank=True, choices=[('snapchat', 'Snapchat'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='platform',
            field=models.CharField(choices=[('snapchat', 'Snapchat'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
